common/compiler_gcc.h
All 64bit PowerPC CPUs handle unaligned accesses reasonably fast, so
set UNALIGNED_ACCESS_IS_FAST.
Decompression of the snappy html test case is almost 50% faster on
POWER9 with this patch applied.
=> Set UNALIGNED_ACCESS_IS_FAST on powerpc64

Makefile
This will be useful in [Nixpkgs](https://github.com/NixOS/nixpkgs/) since for example the library needs to be installed in `/nix/store/{hash}-libdeflate-{version}/lib/libdeflate.so`.
=> Makefile: make the installation prefix configurable

Makefile, lib/zlib_decompress.c, libdeflate.h, programs/test_zlib.c
I need to decompress a zlib-compressed buffer with some additional trailing junk bytes. To handle this, I've added the function `libdeflate_zlib_decompress_ex` with an additional argument `actual_in_nbytes_ret`, analogously to the gzip functions.
Additionally, libdeflate_zlib_decompress now returns successfully in case there are additional trailing bytes in the input buffer after the compressed stream.
=> Add function libdeflate_zlib_decompress_ex

lib/utils.c
Don't assume that lib_common.h and libdeflate.h don't include
<stdlib.h>.  Currently this change doesn't matter unless someone uses
-DFREESTANDING for a Windows build, which isn't supported anyway, but we
might as well clean this up.
Update https://github.com/ebiggers/libdeflate/pull/68
=> lib/utils.c: improve header include order

.travis.yml
Travis CI [recently added support for building builds on 64-bit Arm using AWS Graviton2 instances](https://blog.travis-ci.com/2020-09-11-arm-on-aws). I felt obliged to add it so that Arm support does not bit-rot due to a lack of CI testing.
=> Add arm64 jobs to Travis build matrix.

lib/x86/cpu_features.c
In cpuid() in the '__i386__ && __PIC__' case, the second output operand
is written to before the input operands are used.  So the second output
operand needs the earlyclobber constraint.
=> lib/x86/cpu_features: add missing earlyclobber constraint for cpuid on i386

libdeflate.h
Somehow this was missing from the documentation.
=> libdeflate.h: document invalid compression level error

lib/deflate_compress.c, libdeflate.h, programs/benchmark.c, programs/gzip.c, programs/prog_util.c, programs/test_custom_malloc.c, tools/exec_tests.sh
Some users may require a valid DEFLATE, zlib, or gzip stream but know
ahead of time that particular inputs are not compressible.  zlib
supports "level 0" for this use case.  Support this in libdeflate too.
Resolves https://github.com/ebiggers/libdeflate/issues/86
=> Support level 0, "no compression"

lib/deflate_compress.c
The cutoff for outputting uncompressed data is currently < 16 bytes for
all compression levels.  That isn't ideal, since the higher the
compression level, the more we should bother with very small inputs; and
the lower the compression level, the less we should bother.
Use a formula that produces the following cutoffs:
Level  Cutoff
-----  ------
0      56
1      52
2      48
3      44
4      40
5      36
6      32
7      28
8      24
9      20
10     16
11     12
12     8
Update https://github.com/ebiggers/libdeflate/issues/67
=> lib/deflate_compress: select min_size_to_compress based on level

libdeflate.h
This is supposed to be just 'adler', not 'adler32'.
=> libdeflate.h: fix adler parameter name

programs/benchmark.c, programs/checksum.c, programs/gzip.c, programs/prog_util.c, programs/prog_util.h
Avoid confusion with the GNU extension 'program_invocation_name', which
is described by 'man 3 program_invocation_name'.  The GNU version isn't
supposed to be exposed without defining _GNU_SOURCE, which we don't in
any of the relevant files, but it's best to avoid any confusion.
=> programs: rename program_invocation_name to prog_invocation_name

.gitignore, Makefile
The Makefile didn't trigger a rebuild if some settings changed, e.g.
LDFLAGS or DECOMPRESSION_ONLY.  Fix this.
Also simplify the rebuild logic by not handling the library and programs
separately, as this optimization doesn't seem to be worthwhile.
=> Makefile: add missing settings to rebuild logic

Makefile, scripts/run_tests.sh
Most Linux distributions want dynamic linking rather than static
linking, so support this via 'make USE_SHARED_LIB=1'.
=> Makefile: support linking programs to shared library

lib/arm/matchfinder_impl.h, lib/bt_matchfinder.h, lib/deflate_compress.c, lib/hc_matchfinder.h, lib/matchfinder_common.h, lib/x86/matchfinder_impl.h
Remove the ability of matchfinder_init() and matchfinder_rebase() to
fail due to the matchfinder memory size being misaligned.  Instead,
require that the size always be 128-byte aligned -- which is already the
case.  Also, make the matchfinder memory always be 32-byte aligned --
which doesn't really have any downside.
=> lib/matchfinder: simplify init and rebase

lib/utils.c
This allows these symbols to be overridden by another definition of
these symbols somewhere else in the binary.
Resolves https://github.com/ebiggers/libdeflate/issues/107
=> lib: make freestanding memset() et al. symbols "weak"

.github/workflows/ci.yml
This hopefully will prevent the following error:
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dbg_2.27-3ubuntu1.3_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
=> ci.yml: run 'apt-get update' prior to 'apt-get install'

programs/prog_util.h
Include `sys/types.h` to avoid the following build failure on uclibc:
```
In file included from programs/gzip.c:28:0:
programs/prog_util.h:159:1: error: unknown type name ‘ssize_t’
ssize_t xread(struct file_stream *strm, void *buf, size_t count);
^
```
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> programs/prog_util.h: include sys/types.h

common/compiler_gcc.h
I saw this on Twitter - https://twitter.com/Algunenano/status/1317098341377900550 - claiming this flag to make libdeflate run 20% faster on Wasm.
Indeed, when tried even in a PNG compression benchmark I've observed 10-15% improvement when this flag is enabled.
Even though Wasm might be running on top of a variety of underlying platforms, the spec requires it to support unaligned access, and on majority of platforms it will translate to a faster code. Hence, I think it makes sense to enable this flag by default.
=> Define Wasm as fast unaligned access

lib/arm/adler32_impl.h, lib/arm/crc32_impl.h, lib/arm/matchfinder_impl.h, lib/bt_matchfinder.h, lib/cpu_features_common.h, lib/hc_matchfinder.h, lib/x86/adler32_impl.h, lib/x86/crc32_impl.h, lib/x86/decompress_impl.h, lib/x86/matchfinder_impl.h
A lot of the internal library headers don't have include guards because
they aren't needed.  It might look like a bug, though, and it doesn't
hurt to add them.  So do this.
Update https://github.com/ebiggers/libdeflate/issues/117
=> lib: consistently use include guards

programs/gzip.c, scripts/gzip_tests.sh
The '-t' option of GNU gzip allows checking whether a gzip file is valid
without writing the data anywhere.  It's relatively straightforward to
support in libdeflate-gzip too, so add support for it.
Resolves https://github.com/ebiggers/libdeflate/issues/125
[EB - updated commit message]
=> programs/gzip: add support for the '-t' option (test file integrity)

common/compiler_gcc.h, lib/x86/crc32_pclmul_template.h
now icc oneapi is freeware, so we can test it.
related to #21 
- on ICC, __v2di is defined in immintrin.h
```
In file included from lib/x86/crc32_impl.h(52),
from lib/crc32.c(186):
lib/x86/crc32_pclmul_template.h(107): error: identifier "__v2di" is undefined
const __v2di multipliers_4 = (__v2di){ 0x8F352D95, 0x1D9513D7 };
```
- __v64qi etc are not available on ICC
```
In file included from lib/adler32.c(65):
lib/x86/adler32_impl.h(114): error: identifier "__v64qi" is undefined
const __v64qi multipliers = (__v64qi){
```
tested with `icc (ICC) 2021.2.0 20210228`
=> fix ICC compilation

Makefile
Environment variable DISABLE_SHARED (following convention of --disable-shared
of ./configure script) disables building of shared library and shared lib
symlink. It makes life of downstream maintainer easier when maintaining package
for environment that supports only static libraries.
See https://github.com/NixOS/nixpkgs/pull/144438
=> Add environment variable to disable building shared library

Makefile, libdeflate.pc.in
Doing this from within Make requires either a bunch of sed plus a template file, or use of GNU Make's
file functionality. I opted for the latter. Set the necessary Cflags and Libs (CFLAGS and LFLAGS) based
off compile-time definitions. Depend on the Makefile to pick up version changes.
As noted, we probably want to write the version in `libdeflate.h` based off the VERSION property introduced by this change.
=> Generate a pkg-config support file #140

lib/deflate_decompress.c
Solaris already defines 'len_t' in <sys/types.h>, which causes a build
error.
This typedef isn't important, so just remove it and use u8 directly.
Fixes https://github.com/ebiggers/libdeflate/issues/159
=> deflate_decompress: remove len_t typedef

Makefile
=> buildsys: specify an absolute path for install_name on macOS

Makefile
Haiku doesn't support hard links, so use a symlink instead.
Fixes https://github.com/ebiggers/libdeflate/issues/175
[EB - improved commit message, added '-f' flag so that running install
twice works, and adjusted indentation]
=> Makefile: support Haiku builds

lib/arm/cpu_features.c
Fix the following build error:
In file included from lib/arm/cpu_features.c:130:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/sysctl.h:83:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/ucred.h:104:20: error: use of undeclared identifier 'NGROUPS_MAX'
gid_t   cr_groups[NGROUPS];     /* advisory group list */
=> lib/arm/cpu_features: fix Apple build

Makefile, NEWS.md, README.md, libdeflate.h
Using stdcall in DLL builds but not static library builds (as commit
7e82d450694b did) is problematic because it made it so that
LIBDEFLATE_DLL needs to be defined when linking to libdeflate.dll with
any compiler, rather than just with MSVC as was the case before.
Given that the only reported use case for stdcall is VB6 support, and
VB6 is basically dead, and anyone who *really* wants to still use VB6
could still make a wrapper library to translate between stdcall and
cdecl, let's just always use the default calling convention (cdecl).
Update https://github.com/ebiggers/libdeflate/pull/178
=> Don't use stdcall on 32-bit Windows

.github/workflows/ci.yml
The default MSYS2 installation in GitHub Actions no longer includes
zlib, causing building the test programs to fail.  Switch to using the
setup-msys2 action, and explicitly install zlib.
=> ci.yml: fix the windows-msys2-build-and-test job

lib/decompress_template.h, lib/deflate_decompress.c
Adopt some of the suggestions from Dougall Johnson at
https://dougallj.wordpress.com/2022/08/20/faster-zlib-deflate-decompression-on-the-apple-m1-and-x86/.
Also adopt the "fastloop" strategy similar to that used by zlib, and
make various other improvements and cleanups.
Significant improvements are seen on most platforms I tested:
Arch and CPU          Compiler  Old (MB/s)  New (MB/s)
==================    =======   ==========  ==========
x86_64, Comet Lake    gcc       846         934
x86_64, Zen 1         gcc       832         924
x86_64, Zen 2         gcc       624         684
x86_64, Cascade Lake  gcc       699         706
i386, Comet Lake      gcc       553         717
i386, Zen 1           gcc       531         665
arm64, Apple M1       clang     836         897
arm64, Cortex-A76 …
=> lib: improve decompression performance

lib/arm/matchfinder_impl.h, lib/x86/matchfinder_impl.h
Consistently use the macros from cpu_features.h.
=> lib: don't use CPU feature macros directly

libdeflate.h
This hopefully will address the issue that is being worked around by https://github.com/synopse/mORMot2/commit/87e624cbb7049447.  This isn't really a bug in libdeflate, but rather an ABI incompatibility between gcc and other compilers and programming languages on i386; however, we can work around it.
=> Always use force_align_arg_pointer on i386

Makefile, scripts/make-windows-releases.sh
For the import and static libraries, use the MinGW naming convention (libdeflate.dll.a and libdeflate.a, respectively) instead of the Visual Studio naming convention (libdeflate.lib and libdeflatestatic.lib, respectively).  The original assumption was that the native Windows convention was better.  However, instead people expect the naming convention to reflect the toolchain with which the files were built.
Also change 'make install' to install the DLL into the bin directory instead of the lib directory, again following the MinGW convention.
Fixes https://github.com/ebiggers/libdeflate/issues/190
=> Use MinGW naming convention for Windows libraries

CMakeLists.txt
When WIN32 && !MINGW, call the static library libdeflatestatic.lib so that it doesn't collide with the import library libdeflate.lib.
Fixes https://github.com/ebiggers/libdeflate/issues/236
=> Avoid lib name collision with MSVC builds

.github/workflows/ci.yml, common_defs.h, lib/arm/cpu_features.h, lib/x86/cpu_features.h, programs/prog_util.h, programs/test_util.h
* common_defs: disable annoying MSVC default warnings
* prog_util: disable annoying msvcrt warning
* Support building with Visual Studio + Clang
=> Visual Studio build updates

.github/workflows/ci.yml, lib/bt_matchfinder.h, lib/hc_matchfinder.h, lib/ht_matchfinder.h, lib/x86/adler32_impl.h, lib/x86/cpu_features.c, lib/x86/cpu_features.h, lib/x86/crc32_impl.h, lib/x86/crc32_pclmul_template.h, lib/x86/decompress_impl.h
* lib/matchfinder: make MSVC actually recognize the aligned attribute
* lib/x86: support detecting CPU features with MSVC
* lib/x86: make SSE2 adler32 and matchfinder code work with MSVC
* lib/x86: make AVX2 adler32 code work with MSVC
* lib/x86: make PCLMUL crc32 code mostly work with MSVC
* lib/x86: make bmi2 decompression code work (not very well) with MSVC
* lib/x86: remove vector typedefs that are no longer needed
=> MSVC support for most of lib/x86/

.github/workflows/ci.yml, README.md, common_defs.h, lib/arm/adler32_impl.h, lib/arm/cpu_features.c, lib/arm/cpu_features.h, lib/arm/crc32_impl.h, lib/arm/crc32_pmull_helpers.h, lib/arm/crc32_pmull_wide.h, lib/arm/matchfinder_impl.h, scripts/android_build.sh, scripts/android_tests.sh
* android_build.sh: accept CFLAGS from environment
* android_tests.sh: don't enable crypto on arm32
* lib/arm: partially support detecting CPU features on Windows
* lib/arm: make NEON adler32 and matchfinder code work with MSVC
* lib/arm: make dotprod adler32 code work with MSVC
* lib/arm: make crc32 code work with MSVC
* README: un-bold "strongly"
=> MSVC support for most of lib/arm/ 

lib/adler32.c, lib/crc32.c, lib/deflate_compress.c, lib/deflate_decompress.c, lib/gzip_compress.c, lib/gzip_decompress.c, lib/lib_common.h, lib/utils.c, lib/zlib_compress.c, lib/zlib_decompress.c, libdeflate.h, programs/test_trailing_bytes.c
First, since stdcall support was removed by commit bcc3634037ca ("Don't use stdcall on 32-bit Windows"), we no longer have to worry about the problem described in 3acda56db09a ("Declare __stdcall correctly for MSVC") where some things are needed before the return type and some things are needed after the return type.  Instead we can go back to way libdeflate.h v1.3 was, with just LIBDEFLATEAPI before the return type.
Second, move the definitions only used when building the library into lib_common.h, so that they don't clutter up the public header.
Resolves https://github.com/ebiggers/libdeflate/issues/267
Co-authored-by: Pavel P <pavlov.pavel@gmail.com>
=> Simplify how LIBDEFLATEEXPORT / LIBDEFLATEAPI works

lib/arm/cpu_features.h
Some gcc versions (e.g. 10.2.1) return true for
__has_builtin(__builtin_arm_crc32b) but are affected by the bug mentioned in the comment above the definition of HAVE_CRC32_INTRIN. This causes a build error.  Make it so that the gcc version check is still done when __has_builtin(__builtin_arm_crc32b).
Fixes https://github.com/ebiggers/libdeflate/issues/276
Fixes: 84c76f6f2cf5 ("lib/arm: make crc32 code work with MSVC")
=> lib/arm/cpu_features: re-disable crc32 with buggy gcc versions

lib/arm/cpu_features.h, lib/arm/crc32_impl.h
Fixes https://github.com/ebiggers/libdeflate/issues/280
Fixes: 6db64ab7afd2 ("lib/crc32: CRC-32 optimizations and other improvements")
=> lib/arm/crc32: use crypto target when required due to gcc bug

lib/arm/cpu_features.h
When building for soft float arm32, HAVE_PMULL_INTRIN is being set when it shouldn't be, causing a build error:
#error "NEON intrinsics not available with the soft-float ABI..."
Fix this by making HAVE_PMULL_INTRIN depend on HAVE_NEON_INTRIN, as used to be the case, in order to get the 'defined(__ARM_FP)' dependency,
Fixes https://github.com/ebiggers/libdeflate/issues/282
Fixes: 84c76f6f2cf5 ("lib/arm: make crc32 code work with MSVC")
=> lib/arm/cpu_features: fix build error due to PMULL enabled without NEON

lib/decompress_template.h, programs/CMakeLists.txt, programs/test_invalid_streams.c
When there are more encoded litlen and offset codeword lengths than there are supposed to be based on the earlier fields, return LIBDEFLATE_BAD_DATA instead of ignoring the extra lengths.
This isn't very important, but this aligns the behavior with zlib.
Also add a regression test for this change.
Update https://github.com/ebiggers/libdeflate/issues/288
=> deflate_decompress: return error when too many codeword lengths

.cirrus.yml, .github/workflows/ci.yml, CMakeLists.txt, common_defs.h, lib/adler32.c, lib/arm/cpu_features.c, lib/cpu_features_common.h, lib/crc32.c, lib/deflate_compress.c, lib/deflate_decompress.c, lib/gzip_compress.c, lib/gzip_decompress.c, lib/lib_common.h, lib/utils.c, lib/zlib_compress.c, lib/zlib_decompress.c, programs/CMakeLists.txt, programs/config.h.in, programs/gzip.c, programs/prog_util.c, programs/prog_util.h, programs/test_checksums.c, programs/test_util.c, programs/test_util.h
* programs: drop support for futimes()
* programs: define feature macros automatically in the source code
* programs: use fallback function detection methods for direct compilation
* programs: include libdeflate.h via relative path
* lib: don't use _ANSI_SOURCE
* lib: include libdeflate.h via relative path
* Include libdeflate.h from common_defs.h
* CI: test direct compilation without official build system
=> Improved support for compilation without official build system

.github/workflows/ci.yml, lib/arm/cpu_features.h
* lib/arm/cpu_features: break up the HAVE_CRC32_INTRIN logic
* lib/arm/cpu_features: fix build error on armv6kz and armv7e-m archs
* ci.yml: test building adler32.c and crc32.c with various flags
=> Fix build error on armv6kz and armv7e-m archs

.github/workflows/ci.yml, lib/arm/crc32_impl.h
"Reported" at
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006139
Fixes: fc2ea22b4483 ("lib/arm: add ARM PMULL implementation of CRC-32")
=> lib/arm/crc32_impl: fix build error with Debian armhf gcc

.github/workflows/ci.yml
This avoids the following warning from GitHub Actions:
Node.js 12 actions are deprecated. Please update the following
actions to use Node.js 16: actions/checkout@v2.
=> ci.yml: upgrade to actions/checkout@v3

CMakeLists.txt
With CMake 3.10 and earlier, CMAKE_BUILD_TYPE needs to be explicitly set in the cache for it to take effect.
Also explicitly exclude multi-configuration generators.
See: https://www.kitware.com/cmake-and-the-default-build-type
Fixes https://github.com/ebiggers/libdeflate/issues/301
=> CMakeLists.txt: fix default build type with CMake 3.10 and earlier

scripts/msc_test.bat
This file has been unused since the switch to CMake.
=> scripts: remove obsolete file msc_test.bat

lib/arm/cpu_features.h, lib/x86/cpu_features.h
Unfortunately, checks like __has_builtin(__builtin_ia32_pclmulqdq128) have stopped working properly with clang, starting with clang 15 on x86_64 and clang 16 on arm64.  They now only expand to '1' when the corresponding CPU feature is enabled on the command line.  As a result, a lot of optimized code (mainly for the checksums) is not used.
The reason that libdeflate is doing these checks in the first place is just to exclude old compiler versions that don't support the corresponding set of intrinsics.  So, let's do it the "bad" way and instead check the clang version number directly...
=> lib/cpu_features: fix intrinsic support detection with latest clang

lib/arm/crc32_impl.h
This fixes the arm64 build with clang 16:
lib/arm/crc32_impl.h:270:5: error: always_inline function 'vmull_p64'
requires target feature 'aes', but would be inlined into function
'clmul_u32' that is compiled without support for 'aes'
=> lib/arm/crc32_impl: clang 16 requires "aes", not "crypto"

CMakeLists.txt, lib/deflate_compress.c, lib/deflate_decompress.c, lib/lib_common.h, lib/utils.c, libdeflate.h, programs/test_custom_malloc.c
Allow specifying a custom memory allocator per-(de)compressor, to support use cases where there might be different users of libdeflate in the same process who want to use different memory allocators.
This is a replacement for
https://github.com/ebiggers/libdeflate/pull/312.  I changed the design slightly to be more extensible.  The allocator is specified by a new struct 'libdeflate_options' which is extensible, so the same struct will also work for special compression options/hints, which is something that has been requested in libdeflate before.  (I'm a bit hesitant to add such options, but this least makes a place to put them if it's ever done.)  I also made the pointer to the free function be stored in the (de)compressor struct, so the API for freeing is unchanged.
=> Add support for per-(de)compressor malloc/free functions

lib/deflate_compress.c
* deflate_compress: optimize static blocks at levels 11-12
* deflate_compress: disable large min_match_len on very short inputs
=> Improve compression ratio on very small inputs

lib/x86/cpu_features.c
Make the code more concise and fix some coding style nits.  No change in behavior.
=> lib/x86/cpu_features.c: cleanup

lib/x86/cpu_features.h
A test failure, narrowed down to a problem in deflate_decompress_bmi2(), was reported when libdeflate is built in release mode with MSVC from VS2017.  VS2022 works fine.  Currently, in MSVC builds of libdeflate, the only difference between the bmi2 and default decompression functions is whether the bzhi instrinsics are used (_bzhi_u64() and _bzhi_u32()). But as far as I can tell, libdeflate uses these intrinsics correctly.
Avoid this issue by disabling the use of bzhi intrinsics if the compiler is MSVC before VS2022.
MSVC is closed source, so root causing this issue is not possible.  But one hypothesis is that MSVC may have overlooked that the bzhi intrinsics are supposed to always truncate the index argument to 8 bits, matching the corresponding CPU instructions and as specified by Intel …
=> Don't use bzhi intrinsics on old MSVC versions

scripts/libFuzzer/fuzz.sh
By default libFuzzer only generates inputs up to 4096 bytes in length. To allow more code to be covered, make fuzz.sh specify -max_len=65536 by default, and add an option that allows any value to be specified.
=> fuzz.sh: add --max-len option and increase default length

CMakeLists.txt
While it's possible to limit policy-change commands based on the CMake version(s) where they exist, that's not entirely future-proof. (Some very old policies may someday be removed from later releases.) It's also not necessary, as the most robust (and [recommended](https://cmake.org/cmake/help/v3.27/manual/cmake-policies.7.html#introduction)) approach is to simply test for the existence of the policy _itself_, using `if(POLICY ...)`.
=> CMake: Test policy existence directly

.github/workflows/ci.yml, lib/x86/adler32_impl.h, lib/x86/cpu_features.c, lib/x86/cpu_features.h, lib/x86/crc32_impl.h, lib/x86/crc32_pclmul_template.h, scripts/checksum_benchmarks.sh, scripts/run_tests.sh
* ci.yml: ensure MSVC can find zlib
* lib/x86: disambiguate 512-bit vector from AVX-512F
* lib/x86: fix XCR0 check for AVX-512VL
* lib/x86/adler32: add an AVX-512 implementation
=> lib/x86/adler32: add an AVX-512 implementation

lib/x86/adler32_impl.h, lib/x86/cpu_features.c, lib/x86/cpu_features.h, scripts/checksum_benchmarks.sh, scripts/run_tests.sh
Also revise the AVX512VNNI implementation slightly.
=> lib/x86/adler32: add an AVX-VNNI implementation

lib/x86/adler32_impl.h
After recent changes this is now faster.
=> lib/x86/adler32: use dot product with ones in AVX512VNNI implementation

README.md, common_defs.h, lib/arm/cpu_features.h, lib/x86/adler32_impl.h, lib/x86/cpu_features.c, lib/x86/cpu_features.h, lib/x86/crc32_impl.h, lib/x86/crc32_pclmul_template.h, lib/x86/decompress_impl.h, lib/x86/matchfinder_impl.h
* Drop support for very old versions of gcc and clang
* Get rid of COMPILER_SUPPORTS_TARGET_FUNCTION_ATTRIBUTE
* common_defs.h: fix docs for __has_attribute and __has_builtin
* common_defs.h: simplify checks for very old gcc versions
* lib/arm: simplify checks for very old clang versions
* lib/x86: centralize the intrinsic header inclusions
* lib/x86: remove a workaround for very old gcc versions
* lib/x86: get rid of HAVE_TARGET_INTRINSICS
* lib/x86: simplify checks for very old gcc and clang versions
* lib/x86: simplify by not forcing *_INTRIN on when *_NATIVE
* lib/x86: simplify by not trying to skip target attributes
* lib/x86: remove unnecessary NATIVE macros
* lib/x86: simplify checks for intrinsics
* lib/x86: adding missing MSVC and Apple clang version checks
* lib: make lists of …
=> Drop support for very old compilers and simplify accordingly

lib/adler32.c, lib/arm/adler32_impl.h, lib/x86/adler32_template.h
Make it a macro to avoid any issues with target option mismatches. Also make it do the reduction mod DIVISOR, as all callers want that.
=> lib/adler32: replace adler32_generic_noreduce() with ADLER32_CHUNK()

lib/arm/adler32_impl.h, lib/arm/crc32_impl.h, lib/arm/crc32_pmull_wide.h, lib/decompress_template.h, lib/x86/adler32_impl.h, lib/x86/adler32_template.h, lib/x86/cpu_features.c, lib/x86/cpu_features.h, lib/x86/crc32_impl.h, lib/x86/crc32_pclmul_template.h, programs/test_checksums.c, scripts/checksum_benchmarks.sh
* test_checksums: increase number of long inputs tested
* lib/{adler32,crc32}: misc cleanups
* lib/x86/crc32: more optimizations
=> More CRC-32 and Adler-32 updates

.github/workflows/ci.yml, lib/arm/adler32_impl.h, lib/arm/cpu_features.c, lib/arm/cpu_features.h, lib/arm/crc32_impl.h, lib/arm/crc32_pmull_helpers.h, lib/arm/crc32_pmull_wide.h, lib/arm/matchfinder_impl.h, scripts/checksum_benchmarks.sh, scripts/run_tests.sh
* checksum_benchmarks.sh: handle adler32_arm_neon_dotprod()
* lib/arm: move selection of pmull_wide into arm_cpu_features
* lib/arm: drop the arm32 support for pmull and crc32 instructions
* lib/arm: simplify by not trying to skip target attributes
* lib/arm: fix arm64 builds with -march=armv8-a+nosimd
* lib/arm: centralize the intrinsic header inclusions
* lib/arm: simplify conditions for detecting intrinsics
* lib/arm: use asm fallback when clang intrinsics unusable
* lib/arm: remove unnecessary NATIVE macros
=> ARM CPU feature cleanups

lib/x86/cpu_features.c
Remove some code that should have been removed in commit 44a6510c0d94 ("lib/x86: remove a workaround for very old gcc versions").
=> lib/x86: finish removal of a workaround for very old gcc versions

lib/arm/cpu_features.c, lib/arm/cpu_features.h
Eliminate a redundant preprocessor symbol, as was done in lib/x86/.
=> lib/arm/cpu_features: simplify ifdefs for runtime detection

lib/arm/adler32_impl.h, lib/arm/crc32_impl.h
Resolves https://github.com/ebiggers/libdeflate/issues/369
=> lib/arm: don't use explicit armv8.2-a on gcc 13.2 and later

lib/x86/crc32_impl.h
Resolves https://github.com/ebiggers/libdeflate/issues/371
=> lib/x86/crc32_impl: avoid build error with gcc 8.1 and gcc 8.2

lib/arm/cpu_features.h
vreinterpretq_u64_p128() is missing on aarch64 in gcc 6.
Resolves https://github.com/ebiggers/libdeflate/issues/377
=> lib/arm/cpu_features: require gcc 7.1 for PMULL

lib/arm/adler32_impl.h, lib/arm/crc32_impl.h
Resolves https://github.com/ebiggers/libdeflate/issues/383
=> lib/arm: avoid build error with gcc 13.3 + binutils 2.40

.github/workflows/ci.yml, lib/x86/adler32_impl.h, lib/x86/cpu_features.h, lib/x86/crc32_impl.h
libdeflate failed to build with -mno-evex512 with clang 18+ or gcc 14+ because that flag causes the evex512 feature (which is new in those compiler versions) to have to be explicitly added to functions that use AVX512 with 512-bit vectors.  Add this feature where appropriate.
For the same compiler versions, also add no-evex512 to the functions that use AVX512 + 256-bit vectors so that they are ready for AVX10/256.
Resolves https://github.com/ebiggers/libdeflate/issues/394
=> Specify evex512 and no-evex512 when appropriate

lib/x86/cpu_features.c, lib/x86/cpu_features.h, lib/x86/crc32_impl.h, lib/x86/crc32_pclmul_template.h
In practice, all CPUs that support PCLMULQDQ also support SSE4.1:
Intel: Westmere and later + Silvermont and later
AMD: Bulldozer and later
Therefore, make crc32_x86_pclmulqdq() use SSE4.1 instructions.
To be safe, add an explicit check for SSE4.1 support.  Though as per the above, this is unnecessary in practice (as far as I can tell).
=> lib/x86/crc32: target pclmul,sse4.1 instead of pclmul

lib/x86/cpu_features.h
Avoid build errors when building with -march=native on a system that supports AVX512.
Fixes: 972e73490640 ("lib/x86: Specify evex512 and no-evex512 when appropriate")
=> lib/x86: do not specify no-evex512 when main target has evex512

CMakeLists.txt
CMake 3.31 warns:
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
=> Increase minimum CMake version to 3.10

.github/workflows/ci.yml
This combination no longer builds due the following error:
error MSB8037: The Windows SDK version 10.0.26100.0 for Desktop C++ ARM Apps was not found.
=> ci.yml: stop testing Visual Studio + ARM32

lib/x86/crc32_impl.h, lib/x86/crc32_pclmul_template.h
The specifications for _mm256_castsi128_si256() and _mm512_castsi128_si512() are bugged, as they leave the high bits undefined instead of zeroed as would be expected.  Separate intrinsics _mm256_zextsi128_si256() and _mm512_zextsi128_si512() were later added to allow working around this defect.  Use them.
This fixes incorrect CRC checksums produced by
crc32_x86_vpclmulqdq_avx512_vl512() when built with 'clang -O0'. Other cases are not known to have been affected.
Resolves https://github.com/ebiggers/libdeflate/issues/403 Fixes: 5f2a0b4beca9 ("lib/x86/crc32: add VPCLMULQDQ implementations of CRC-32")
=> lib/x86/crc32: fix undefined behavior in VPCLMULQDQ optimized functions

.github/workflows/ci.yml
GitHub Actions will drop support for ubuntu-20.04 soon.
=> ci.yml: bump the Ubuntu versions

.github/workflows/ci.yml, common_defs.h
=> Add basic support for Windows ARM64EC

CMakeLists.txt
To enable iOS-derived compilations, I introduced a new flag, `LIBDEFLATE_FRAMEWORK`, which is set to `FALSE` by default. I also defined the required properties for framework generation, as described in the [CMake documentation](https://cmake.org/cmake/help/latest/prop_tgt/FRAMEWORK.html#prop_tgt:FRAMEWORK).
Building is successful using the following commands:
```bash
cmake -S. -B build -DLIBDEFLATE_FRAMEWORK=ON -DLIBDEFLATE_BUILD_SHARED_LIB=OFF -DCMAKE_SYSTEM_NAME=iOS
sudo cmake --build build --target install --config Release
```
=> Add support for Apple framework builds

lib/x86/adler32_impl.h, lib/x86/cpu_features.h, lib/x86/crc32_impl.h
gcc-16 `master` branch dropped support for `evex512` as:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=c052a6f4a1c803cb92147ff98fb91cf3511e0856
As a result libdeflate build started failing as:
In file included from /build/source/lib/adler32.c:28:
/build/source/lib/x86/adler32_template.h:135:12: error: attribute 'target' argument 'no-evex512' is unknown
135 | ADD_SUFFIX(reduce_to_32bits)(vec_t v_s1, vec_t v_s2, u32 *s1_p, u32 *s2_p)
|            ^~~~~~~~~~~~~~~~
The change adds upper build to `evex512` for `gcc`.
=> lib/x86/cpu_features.h: drop evex512 on gcc-16

.github/workflows/ci.yml
Don't use windows-2019, which GitHub Actions no longer supports. Replace windows-2022 with windows-latest, which currently means the same thing, but it ensures we stay on the latest version in the future.
=> ci.yml: Use windows-latest for windows-visualstudio-build-and-test
