ebiggers/libdeflate

.cirrus.yml

[EB - changed script to use the new 'make check' target]

Test freebsd with cirrus-ci

---

Makefile

Also added `*.dylib` to `clean` target

Install shared lib symlink as dylib on macOS

---

Makefile

Resolves https://github.com/ebiggers/libdeflate/pull/72

Makefile: support 'install' and 'uninstall' with Windows builds

---

README.md

Resolves https://github.com/ebiggers/libdeflate/issues/70

README.md: add links to third-party bindings

---

Makefile.msc

Makefile.msc: fix clean task

---

programs/benchmark.c

Update https://github.com/ebiggers/libdeflate/issues/120

benchmark: clarify what the -g and -z options do

---

.github/workflows/ci.yml

This is no longer supported by GitHub Actions.

ci.yml: remove ubuntu-16.04

---

lib/deflate_compress.c

For fastest, greedy, lazy, and lazy2: save memory by reducing the length
of the sequence store, and forcing a split if it is filled.
For fastest: increase the max block length, but use a relatively short
sequence store that will cause shorter blocks to be used often.
For all: allow the final block to exceed the soft maximum length if it
avoids having to create a block below the minimum length.

deflate_compress: adjust block splitting conditions

---

.github/workflows/android.yml

Reference:
https://developer.android.com/ndk/guides/other_build_systems

add GitHubActions to build for android

---

Makefile

Enables building in [MSYS2 Clang x86/x86_64/aarch64 environments](https://www.msys2.org/docs/environments/).
This is from the current [MSYS2 libdeflate package patch](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libdeflate/001-libdeflate-makefile-mingw-fix.patch) (ignore the static and shared library related differences for now).

Support building with LLVM toolchain on Windows

---

Makefile
programs/prog_util.c
scripts/check.sh
scripts/gzip_tests.sh
scripts/run_tests.sh

* prog_util: make O_NOFOLLOW work on macOS
* prog_util: detect mmap unsupported on macOS
* gzip_tests.sh: drop workaround for Travis CI
* Make run_tests.sh work on macOS (tested on macOS 12.0.1)

Make run_tests.sh work on macOS

---

libdeflate.h

Update https://github.com/ebiggers/libdeflate/issues/102

Improve documentation for libdeflate_deflate_compress()

---

README.md

Add Perl to bindings list

---

programs/gzip.c

Fixes https://github.com/ebiggers/libdeflate/issues/230

programs/gzip: fix build error on OpenIndiana

---

CMakeLists.txt
libdeflate.pc.in

(As requested at
https://github.com/ebiggers/libdeflate/pull/232#issuecomment-1318977419.)

Make the pkg-config file relocatable again

---

common_defs.h
lib/adler32.c
lib/arm/adler32_impl.h
lib/arm/cpu_features.c
lib/arm/cpu_features.h
lib/arm/crc32_impl.h
lib/arm/crc32_pmull_helpers.h
lib/crc32.c
lib/deflate_decompress.c
lib/matchfinder_common.h
lib/x86/cpu_features.c
lib/x86/cpu_features.h
lib/x86/decompress_impl.h

Co-authored-by: Shawn Hoffman <godisgovernment@gmail.com>

Target architecture macro for intel/arm archs for gcc/msvc

---

libdeflate.h

Update https://github.com/ebiggers/libdeflate/issues/267

libdeflate.h: includes should be outside of extern "C" block

---

.github/workflows/ci.yml
programs/CMakeLists.txt

* programs/CMakeLists.txt: fix install on Windows
* ci.yml: test install whenever possible

Update CMakeLists.txt to fix install on Windows

---

README.md

I created a Nim wrapper for this fantastic library. Can you include it in the README?

README.md: add Nim to bindings list

---

lib/x86/cpu_features.c

Mark the asm block containing the xgetbv instruction with 'volatile' so that compiler optimizations can't move it out from under the check for OSXSAVE support.
This isn't known to have actually been happening, but it's theoretically possible.  (It did happen in another project where I use a modified version of this code that was more friendly to compiler optimizations.)

lib/x86/cpu_features: ensure xgetbv not executed when unsupported

---

README.md

This binding isn't complete (it only implements compression APIs, since those are easiest and most impactful for my use case), but it may be useful to others nonetheless.

Add PHP binding to the list

---

lib/deflate_compress.c
libdeflate.h

* deflate_compress: reorganize some code in deflate_flush_block()
* deflate_compress: include header cost in deflate_flush_block()
* deflate_compress: improve output overflow handling

deflate_compress: improve output overflow handling

---

lib/deflate_compress.c
lib/deflate_decompress.c

Fix compatibility with some DEFLATE decompressors that don't correctly handle some edge cases in the DEFLATE specification.
Fixes https://github.com/ebiggers/libdeflate/issues/323

deflate_compress: always generate complete Huffman codes
